language: go

env:
  - TEST_DIR=.
  - TEST_DIR=rest

install: cd ${TRAVIS_BUILD_DIR}/${TEST_DIR} && make build

before_script: go get gopkg.in/check.v1

script: cd ${TRAVIS_BUILD_DIR}/${TEST_DIR} && make test
